services:
  web:
    restart: unless-stopped
    image: hjcasayas/portfolio:v1.4.0
    build:
      dockerfile: ./Dockerfile
      target: production
      context: .
      tags:
        - hjcasayas/portfolio:latest
        - hjcasayas/portfolio:v1.4.0
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - ./.env
    environment:
      - MINIO_END_POINT=${MINIO_END_POINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_PERSONAL_BUCKET_NAME=${MINIO_PERSONAL_BUCKET_NAME}
      - MINIO_RESUME_FILE_NAME=${MINIO_RESUME_FILE_NAME}
  cloudflare:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./.env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
