services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces/hjcasayas:cached
      - workspace-node_modules:/workspaces/hjcasayas/node_modules
      - frontend-next:/workspaces/hjcasayas/.next
    command: sleep infinity
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ../
      target: development
    volumes:
      - ../:/app
      - workspace-node_modules:/app/node_modules
      - frontend-next:/app/.next
    restart: always
    ports:
      - 3000:3000
    depends_on:
      dev-container:
        condition: service_started

volumes:
  workspace-node_modules:
  frontend-next:
